spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer_service
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**
          filters:
            - StripPrefix=1 # StripPrefix: 호출된 path에서 몇 개의 prefix를 제거할 것인지 지정
        - id: order_service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
