spring:
  application:
    name: discovery-service # 마이크로서비스 간 unique ID로 사용
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false # registry에 자신을 등록할지에 대한 여부
    fetch-registry: false # registry에 있는 정보를 가져올지에 대한 여부
